# Generated by Django 3.2.12 on 2022-03-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstCategory',
            fields=[
                ('first_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_category_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'first_categories',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('linkUrl', models.URLField()),
                ('imageUrl', models.URLField()),
            ],
            options={
                'db_table': 'magazines',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('second_cateogry_id', models.AutoField(primary_key=True, serialize=False)),
                ('second_category_name', models.CharField(max_length=10)),
                ('first_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.firstcategory')),
            ],
            options={
                'db_table': 'second_categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=10)),
                ('image_url', models.URLField()),
                ('request_count', models.IntegerField()),
                ('second_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.secondcategory')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['request_count'],
            },
        ),
    ]
