# Generated by Django 3.2.12 on 2022-03-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_auto_20220313_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='남자', max_length=2),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
