# Generated by Django 3.2.12 on 2022-03-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20220314_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstcategory',
            name='first_category_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
