# Generated by Django 3.2.12 on 2022-03-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowhow',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.user'),
            preserve_default=False,
        ),
    ]
