# Generated by Django 3.2.12 on 2022-03-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_knowhow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowhow',
            name='user',
        ),
        migrations.AddField(
            model_name='knowhow',
            name='pro',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainApp.pro'),
            preserve_default=False,
        ),
    ]
