# Generated by Django 3.2.12 on 2022-03-14 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20220314_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowhow',
            name='pro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='mainApp.pro'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mainApp.user'),
        ),
    ]
