# Generated by Django 3.2.12 on 2022-03-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20220314_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pro',
            name='service',
        ),
        migrations.AddField(
            model_name='pro',
            name='hired_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.pro'),
        ),
        migrations.AlterField(
            model_name='pro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainApp.user'),
        ),
    ]
