# Generated by Django 3.2.12 on 2022-03-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20220314_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowhow',
            name='service',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mainApp.service'),
            preserve_default=False,
        ),
    ]
