# Generated by Django 3.2.12 on 2022-03-16 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20220315_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='proservice',
            name='item_img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='proservice',
            name='price',
            field=models.IntegerField(default=10000, null=True),
        ),
        migrations.AddField(
            model_name='proservice',
            name='status',
            field=models.CharField(default='inprogress', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='proservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mainApp.proservice'),
        ),
    ]
