# Generated by Django 3.2.12 on 2022-03-16 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_auto_20220316_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowhow',
            name='pro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='mainApp.pro'),
        ),
    ]
