# Generated by Django 3.2.12 on 2022-03-16 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_knowhow_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowhow',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='mainApp.service'),
        ),
    ]
