# Generated by Django 3.2.12 on 2022-03-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_proservice_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proservice',
            name='item_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
