# Generated by Django 3.2.12 on 2022-03-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_alter_proservice_item_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('proservice',)},
        ),
    ]
